### ISSUE TITLE
Wrong package on NuGet

### ISSUE THREAD

**Issue by mbp** [rebus-org/Rebus.CastleWindsor#2]
It seems by mistake there are 2 packages on NuGet

![image](https://user-images.githubusercontent.com/77322/32101653-61923618-bb19-11e7-88e3-50101ef56c08.png)

Probably version 4.0.0 should have been added as a new version to the `Rebus.Castle.Windsor` package and `Rebus.CastleWindsor` should never have existed.

**Comment by mookid8000** [comment]
damn! That must have crept in when I updated the `.csproj` to the new format where all nuspec-stuff is embedded in the project file.... let me just take a look

**Comment by mookid8000** [comment]
I have fixed it now – since the project name and the NuGet package ID were not the same (which is pretty stupid, and not intentional btw.), I had to add
```xml
<PackageId>Rebus.Castle.Windsor</PackageId>
```
to `Rebus.CastleWindsor.csproj`

Thanks for letting me know 😁

**Comment by mbp** [comment]
Thanks! :-) That was fast.

**Comment by mookid8000** [comment]
I have unlisted the Rebus.CastleWindsor package from NuGet.org btw – from the download count, it seems like only a few people found it.

And here's a note for those people (in case they come by this issue in the future): The `Rebus.CastleWindsor` package was published by mistake – the correct name is (and always has been) `Rebus.Castle.Windsor` (i.e. with a `.` between `Castle` and `Windsor`).

Therefore: If you have already added `Rebus.CastleWindsor`, your package restore will still work, but you will not be able to update the package. It is also not possible to install this package into new projects.

You should install `Rebus.Castle.Windsor` instead, because that's the real package 👍 

I hope it's clear now 😄
